engines:
  pylint:
    enabled: true
    config:
      max-line-length: 88
      max-function-length: 50
      max-class-length: 200
  black:
    enabled: true
  mypy:
    enabled: true
  isort:
    enabled: true
  duplication:
    enabled: true
